name: medcontrol
description: MedControl – Controle de medicamentos com SQLite + API
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  # Banco local SQLite
  sqflite: ^2.3.2
  path: ^1.9.0
  # Comunicação com a API Dart
  http: ^1.2.1
  # Datas
  intl: ^0.20.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
